name: Package

on: [push]

jobs:
  pyinstaller-build:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "secrets/credentials.json"
          json: ${{ secrets.CREDENTIALS_JSON }}
      - name: Create single file executable for ${{ matrix.os }}
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'Philippe_CalSync${{ matrix.os }}.exe'
      